### ISSUE TITLE
Error with null values

### ISSUE THREAD

**Issue by jobelenus** [Polarisation/vue-nested-list#1]
I'm seeing when a JSON object has nulls as values for keys that the plugin throws errors. The specific error it throws is: "Invalid prop: type check failed for prop "content". Expected Object, got Null". I've been able to fix it by replacing the `NestedDl` template line:

`+"<nested-list v-bind:content='value' v-bind:max-length='maxLength'></nested-list>"`

With

`+"<nested-list v-bind:content='value || \"\"' v-bind:max-length='maxLength'></nested-list>"`

You may prefer a different solution but I wanted to let you know of the bug anyhow, as null is a valid parameter for JSON.

**Comment by Polarisation** [comment]
Thanks, good catch. I solved it with a null check rather than changing the binding

**Comment by jobelenus** [comment]
Awesome, I see the 1.0.1 release on NPM, this is included in there?

**Comment by Polarisation** [comment]
Yep
